#!/usr/bin/env bash

# Clone bare repository in a nice way
# Hide all git meta in .bare

set +x

usage() {
  echo "Usage: git bare-clone <git-repo-url> [target-directory]"
}
error() {
  echo "Error: $@"
}
[[ $# -lt 1 ]] && usage && exit 1
if ! [[ $1 =~ "git@github" ]];
then
    error "'$1' is not a git url" 
    usage 
    exit 1
fi

target=${2:-.}
git_path=$1

echo "Target ${target}"

git clone --bare ${git_path} "$target/.bare"
pushd "$target/.bare" > /dev/null
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
popd > /dev/null
echo "gitdir: $target/.bare" > $target/.git
echo "done"

#pushd .bare
#git clone --bare $1 .bare
