#!/bin/zsh
set -e
declare -a git_gems
git_gems=()
bundle list | awk '/^* (.*) \(.* .*\)/ { print $2; }' | while read line ; do git_gems+=($line) ; done
proc=`cat Procfile | cut -d : -f 1`
cmd="rerun --pattern '{**/*.{rb,ru,json,txt,scss,sass},Gemfile,Gemfile.lock,Rakefile,*.gemspec}' -c --signal INT --dir '."
for i in "${git_gems[@]}"; do
  gem_path=$(bundle info "$i" --path)
  cmd+=",$gem_path"
done
cmd+="' foreman run $proc"
echo $cmd
eval $cmd
